# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Czym Chata Bogata
email: czymchatabogatazzt@gmail.com
url: "https://czymchatabogata.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  Znajdź pomysł na idealną wycieczkę bez tracenia czasu na planowanie! Odkrywaj z nami Dolny Śląsk i okolice. Zainspiruj się naszymi gotowymi trasami pełnymi wyjątkowych miejsc.
twitter_username: username
github_username: czymchatabogata
minimal_mistakes_skin: "sunrise"
search: true
logo: "/assets/images/bio-photo.jpg"
locale: "pl-PL"

# Build settings
markdown: kramdown
remote_theme: czymchatabogata/minimal-mistakes@czymchatabogata-20230113
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

google_site_verification: Tl7NtRqbYBOq-m4Y2yMEkQI3ep7m709S_s0ArPI-deQ

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Czym Chata Bogata"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Znajdź pomysł na idealną wycieczkę bez tracenia czasu na planowanie! Odkrywaj z nami Dolny Śląsk i okolice. Zainspiruj się naszymi gotowymi trasami pełnymi wyjątkowych miejsc."
  links:
  #  - label: "Website"
  #    icon: "fas fa-fw fa-link"
  #    url: "https://czymchatabogata.pl"
    - label: "Email"
      icon: "fab fa-fw fa-envelope"
      url: "mailto:kontakt@chatabogata.turystyka.pl"      
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/czymchatabogatazzt/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/people/Czym-Chata-Bogata/61569076540376/"  
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@CzymChataBogataZZT"    
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://www.tiktok.com/@czymchatabogatazzt"              

footer:
  links:
    - label: "Email"
      icon: "fab fa-fw fa-envelope"
      url: "mailto:kontakt@chatabogata.turystyka.pl"    
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/czymchatabogatazzt/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/people/Czym-Chata-Bogata/61569076540376/" 
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@CzymChataBogataZZT"    
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://www.tiktok.com/@czymchatabogatazzt"        

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-TXK6QJ5HB3"
    anonymize_ip: false # default


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      classes: wide
      header:
        image: "/assets/images/header-1600x400.jpg"      
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide
      header:
        image: "/assets/images/header-1600x400.jpg"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
